import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

[window]
dynamic_title = true
decorations = "full"
startup_mode = "Windowed"
opacity = 0.7
blur = true
padding = { x = 5, y = 5 }
dynamic_padding = true

[window.dimensions]
columns = 80
lines = 24

[font]
normal = { family = "FiraCode Nerd Font", style = "Retina" }
bold = { family = "FiraCode Nerd Font", style = "Retina" }
italic = { family = "FiraCode Nerd Font", style = "Retina" }
size = 16.0

[env]
TERM = "xterm-256color"
