
[window]
dynamic_title = true
decorations = "full"
startup_mode = "Windowed"
opacity = 0.8
blur = true
padding = { x = 5, y = 5 }
dynamic_padding = true
option_as_alt = "Both"

[window.dimensions]
columns = 80
lines = 24

[font]
normal = { family = "FiraCode Nerd Font", style = "Retina" }
bold = { family = "FiraCode Nerd Font", style = "Medium" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
size = 16.0

[cursor]
style = { shape = "Beam", blinking = "Off" }
vi_mode_style = { shape = "Block", blinking = "Off" }

[env]
TERM = "xterm-256color"

[general]
import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]
